version: "3.1"

services:
    minio:
      image: 'bitnami/minio:latest'
      ports:
        - '9000:9000'
      environment:
        - MINIO_ACCESS_KEY=minio-key
        - MINIO_SECRET_KEY=minio-secret
      volumes:
        - y-analyzer:/var/lib/minio/data
      networks:
        - dev

    postgres:
      image: postgres
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: videos-data
      volumes:
        - y-analyzer:/var/lib/postgresql/data
      networks:
        - dev

volumes:
  y-analyzer:
    external: true
networks:
  dev: