service: youtube-analyzer

custom:
  channelsBucket: analyzer-channels
#  pythonRequirements:
#    dockerizePip: non-linux

package:
  exclude:
    - node_modules/**

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  region: eu-central-1
  stage: develop

functions:
  starter:
    handler: handler.run
    environment:
      BUCKET_NAME: ${self:custom.channelsBucket}
    events:
      - schedule: rate(5 minutes)


plugins:
  - serverless-python-requirements