"""apikeys

Revision ID: 2b5160bcd04a
Revises: 66ad0fbfaca5
Create Date: 2020-07-23 19:49:59.297982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5160bcd04a'
down_revision = '66ad0fbfaca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountKey',
    sa.Column('key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accountKey')
    # ### end Alembic commands ###
