"""kv

Revision ID: 66ad0fbfaca5
Revises: 591372ec0eae
Create Date: 2020-07-20 20:52:05.241589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ad0fbfaca5'
down_revision = '591372ec0eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kv',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('video', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'channel_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('kv')
    # ### end Alembic commands ###
